version: '2'  
services:
  nodered:
    container_name: node-red
    image: nodered/node-red-docker:v8
    restart: unless-stopped
    volumes:
      - '/etc/localtime:/etc/localtime'
      - node-red-dev:/data
    environment:
      - TZ=America/New_York      
    ports:
      - 1880:1880
    networks:
      - home_automation
    labels:
      - traefik.backend=node-red
      - traefik.frontend.rule=Host:node-red.thehibbs.net
      - traefik.docker.network=home_automation    
      - traefik.port=1880      
  mosquitto:
    container_name: mqtt-mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - '/containers/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - home_automation
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:0.90.1
    restart: unless-stopped
    volumes:
      - /containers/hass/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    environment:
      - TZ=America/New_York      
      - PUID=1000
      - PGID=1000
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /containers/hass/config/appdaemon/conf:/conf
    ports:
      - 5050:5050
    labels:
      - traefik.backend=appd
      - traefik.frontend.rule=Host:appd.thehibbs.net
      - traefik.docker.network=home_automation    
      - traefik.port=5050       
    networks:
      - home_automation
  tasmoadmin:
    container_name: tasmo-admin
    image: raymondmm/tasmoadmin:latest
    restart: unless-stopped
    volumes:
      - tasmoadmin_data:/data
    ports:
      - 5555:80
    #environment:
    labels:
      - traefik.backend=tasmo-admin
      - traefik.frontend.rule=Host:tasmo-admin.thehibbs.net
      - traefik.docker.network=home_automation    
      - traefik.port=80 
    networks:
      - home_automation     
networks:
  home_automation:
    external: true

volumes:
  node-red-dev:
  tasmoadmin_data:
