version: '2'

services:
  postgresql:
    image: postgres:latest
    container_name: FressRSS-DB
    restart: unless-stopped
    volumes:
    - fresh_rss_db:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=freshrss
    - POSTGRES_PASSWORD=${DB_PASS}
    - POSTGRES_DB=freshrss
    networks:
      - proxy
  freshrss:
    image: freshrss/freshrss:latest
    container_name: FreshRSS
    restart: unless-stopped
    depends_on:
      - postgresql
    ports:
      - 8090:80
    networks:
      - proxy
    volumes:
      - fresh_rss_app:/var/www/FreshRSS/data
    labels:
      - traefik.backend=freshrss
      - traefik.frontend.rule=Host:rss.thehibbs.net
      - traefik.docker.network=proxy
      - "traefik.default.protocol=http"
      - "traefik.frontend.entryPoints=http,https"      
      - traefik.port=80      
    environment:
      - CRON_MIN=*/20
volumes:
  fresh_rss_db:
  fresh_rss_app:
networks:
  proxy:
    external: true