version: '2'  
services: 
  influxdb:
    container_name: influxDB
    image: influxdb:latest
    restart: unless-stopped
    volumes:
      - influxdb_official:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003      
    networks:
      - proxy
    labels:
      - traefik.backend=influxdb
      - traefik.frontend.rule=Host:influxdb.thehibbs.net
      - traefik.docker.network=proxy
      - "traefik.default.protocol=http"
      - "traefik.frontend.entryPoints=http,https"      
      - traefik.port=8083
  chronograf:
    container_name: chronograf
    image: chronograf:latest
    restart: unless-stopped
    volumes:
      - chronograf_official:/var/lib/chronograf
    ports:
      - 8888:8888    
    networks:
      - proxy
    labels:
      - traefik.backend=chronograf
      - traefik.frontend.rule=Host:crono.thehibbs.net
      - traefik.docker.network=proxy
      - "traefik.default.protocol=http"
      - "traefik.frontend.entryPoints=http,https"      
      - traefik.port=8888                  
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana_official:/var/lib/grafana
    ports:
      - 3000:3000    
    networks:
      - proxy
    labels:
      - traefik.backend=grafana
      - traefik.frontend.rule=Host:grafana.thehibbs.net
      - traefik.docker.network=proxy
      - "traefik.default.protocol=http"
      - "traefik.frontend.entryPoints=http,https"      
      - traefik.port=3000
networks:
  proxy:
    external: true

volumes:
  influxdb_official:
  grafana_official:
  chronograf_official: