version: '2'  
services:
  pihole:
    container_name: pi-hole
    hostname: TheHibbsPiHole
    image: pihole/pihole:latest
    restart: unless-stopped
    volumes:
      - pi-hole-dev2:/etc/pihole
      - pi-hole-dev2-dns:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 192.168.2.101
    networks:
      default:
        ipv4_address: ${SERVER_IP}
    environment:
      - ServerIP=${SERVER_IP}
      - TZ=America/New_York
      - DNS1=${DNS1}
      - DNS2=${DNS2}
      - WEBPASSWORD=${PIHOLE_PASS}
      - VIRTUAL_HOST=TheHibbsPiHole
volumes:
  pi-hole-dev2:
  pi-hole-dev2-dns:
  
networks:
  default:
    external:
      name: macvlan20