version: '2'  
services:   
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    networks:
      - internal
  # Container management WebGUI    
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.${DOMAIN_NAME}
      - traefik.docker.network=proxy
      - traefik.port=9000
      - traefik.domain=${DOMAIN_NAME}    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/portainer:/data
    ports:
      - 9000:9000
    networks:
      - internal
      - proxy
  #armviz:
  #  container_name: ArmViz
  #  restart: always
  #  image: ytechie/armviz:v2
  #  labels:
  #    - traefik.backend=armviz
  #    - traefik.frontend.rule=Host:armviz.${DOMAIN_NAME}
  #    - traefik.docker.network=proxy
  #    - traefik.port=80
  #    - traefik.domain=${DOMAIN_NAME}
  #  networks:
  #    - proxy
  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    labels:
      - traefik.backend=organizr
      - traefik.frontend.rule=Host:portal.${DOMAIN_NAME}
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.domain=${DOMAIN_NAME}
    volumes:
      - /containers/organizr:/config
    ports:
      - 8091:80
    networks:
#      - internal
      - proxy
  traefik:
    container_name: traefik
    image: traefik
    command: --api --docker --logLevel=ERROR
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:monitor.${DOMAIN_NAME}
      - traefik.docker.network=proxy
      - traefik.port=8080
      - traefik.domain=${DOMAIN_NAME}    
    networks:
      - proxy
      - media
      - home_automation
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/traefik/traefik.toml:/traefik.toml
      - /containers/traefik/acme.json:/acme.json          
networks:
  proxy:
    external: true
  media:
    external: true
  home_automation:
    external: true    
  internal:
    external: false      