version: '2'  
services:   
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.thehibbs.net
      - traefik.docker.network=proxy
      - traefik.port=9000
      - traefik.domain=thehibbs.net    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/portainer:/data
    ports:
      - 9000:9000
    networks:
      - internal
      - proxy
  armviz:
    container_name: ArmViz
    restart: always
    image: ytechie/armviz:v2
    labels:
      - traefik.backend=armviz
      - traefik.frontend.rule=Host:armviz.thehibbs.net
      - traefik.docker.network=proxy
      - traefik.port=80
      #- traefik.frontend.entryPoints=http
      - traefik.domain=thehibbs.net
    networks:
#      - internal
      - proxy
  organizr:
    container_name: organizr-dev
    restart: always
    image: lsiocommunity/organizr
    labels:
      - traefik.backend=organizr
      - traefik.frontend.rule=Host:portal.thehibbs.net
      - traefik.docker.network=proxy
      - traefik.port=80
      #- traefik.frontend.entryPoints=http
      - traefik.domain=thehibbs.net
    volumes:
      - /containers/organizr:/config
    ports:
      - 8091:80
    networks:
      - internal
      - proxy
  traefik:
    container_name: traefik-dev
    image: traefik
    command: --api --docker --logLevel=ERROR
    environment:
      - AZURE_CLIENT_ID=5623c202-aafa-487d-a675-8dfe166a3233
      - AZURE_CLIENT_SECRET=4HcawtivCmxDGEbYtsNUB0UH1Q8gd2zpmnSPv5TikrY=
      - AZURE_SUBSCRIPTION_ID=f86378f4-326c-4d65-8567-26c6c3e223c1
      - AZURE_TENANT_ID=a47c6ab1-f36d-4408-b949-bdc2d688972d
      - AZURE_RESOURCE_GROUP=ExternalProd
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:monitor.thehibbs.net
      - traefik.docker.network=proxy
      - traefik.port=8080
      #- traefik.frontend.entryPoints=http
      - traefik.domain=thehibbs.net    
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/traefik/traefik.toml:/traefik.toml
      - /containers/traefik/acme.json:/acme.json          
networks:
  proxy:
    external: true
  internal:
    external: false      