version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    container_name: mysql
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=9s5qJQVA7tj7JE
      - MYSQL_PASSWORD=9s5qJQVA7tj7JE
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    container_name: NextCloud
    image: 192.168.0.104:5000/hblnextcloudsmb:latest
    ports:
      - 1118:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html  
    networks:
      - proxy
      - default
    labels:
      - traefik.backend=cloud
      - traefik.frontend.rule=Host:cloud.thehibbs.net
      - traefik.docker.network=proxy
      - "traefik.default.protocol=http"
      - "traefik.frontend.entryPoints=http,https"      
      - traefik.port=80    
    restart: always

networks:
  proxy:
    external: true